---
title: "Data Cleaning"
author: "Uluc Kadioglu"
date: "11/2/2020"
output: html_document
---

https://wyatthurt.shinyapps.io/water_conflict/
https://shiny.rstudio.com/reference/shiny/1.5.0/

From Wyatt Hurt to Everyone: (8:19 PM)

library(state)
https://www.rdocumentation.org/packages/datasets/versions/3.6.2/topics/state
state.x77
https://usmap.dev/
data(statepop)

From Wyatt Hurt to Everyone: (8:25 PM)

https://davidkane9.github.io/PPBDS/maps.html



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(bigrquery)
library(tidytext)
library(ggrepel)
library(wordcloud2)
library(datapasta)
library(webshot)
library(htmlwidgets)
library(mapview)
library(ggmap)
library(sf)
library(rstanarm)
library(lubridate)
library(tigris)
library(wordcloud2)
library(usmap)
library(gtsummary)
library(gt)
library(broom.mixed)

```

```{r}
ufo <- read_rds("shiny_app/data/nuforc_reports.rds") %>%
            filter(state %in% state.abb) %>%
            drop_na()

View(ufo)
```

```{r}

ufo_text_only <- read_rds("shiny_app/data/nuforc_reports.rds") %>%
  select(text) %>%
  drop_na()

rgb2hex <- function(r,g,b) rgb(r, g, b, maxColorValue = 255)

colour_scheme <- c(rgb2hex(0,144,218),
                  rgb2hex(219,10,91),
                  rgb2hex(0,163,173),
                  rgb2hex(0,97,160),
                  rgb2hex(96,37,169))

stopwords2 <- tibble(word = c("I",
                              "there",
                              "were",
                              "it",
                              "3",
                              "30",
                              "20",
                              "5",
                              "100",
                              "2",
                              "15",
                              "pd",
                              "note",
                              "10",
                              "nuforc",
                              "1",
                              "4",
                              "8",
                              "7",
                              "6",
                              "9",
                              "12",
                              "50"))

copied_text <- datapasta::vector_construct()

copied_text %>%
  enframe(name = "line", value = "text") %>% # Convert text into a tibble
  tidytext::unnest_tokens(output = word, # tokenise - one word per row
                          input = text,
                          token = "words") %>%
  mutate_at("word", ~str_replace_all(.,"clouds","cloud")) %>% # Manual word stemming
  anti_join(tidytext::stop_words, by = "word") %>% # Remove stop words using tidytext
  anti_join(stopwords2, by = "word") %>% # Remove additional stop words
  count(word, name = "freq") %>%
  filter(freq >= 50) %>%
  wordcloud2::wordcloud2(size = 1,
                         ellipticity = 1,
                         rotateRatio = 0,
                         color = sample(colour_scheme, nrow(.), replace = TRUE))

```

```{r map}
# https://cran.r-project.org/web/packages/usmap/usmap.pdf

meteor_locations <- read_csv("shiny_app/data/meteorite-landings.csv") %>%
  arrange(desc(year)) %>%
  select(name, year, reclat, reclong, GeoLocation) %>%
  filter(!GeoLocation == "(0.000000, 0.000000)") %>%
  select(reclat, reclong) %>%
  filter(reclong >= -125 & reclong <= -66 & reclat <= 49 & reclat >= 25)

ufo_locations <- ufo %>%
  select(city_latitude, city_longitude) %>%
  head(10) %>%
  filter(city_longitude >= -125 & city_longitude <= -66 & city_latitude <= 49 & city_latitude >= 25)

ufo_locations_sf <- st_as_sf(ufo_locations, coords = c("city_longitude", "city_latitude"), crs = 4326)
meteor_locations_sf <- st_as_sf(meteor_locations, coords = c("reclong", "reclat"), crs = 4326)

mapview(ufo_locations_sf)

# Maybe a map that has both meteor landings and UFO sightings together.
```

```{r alcohol}

alcohol <- read.csv("shiny_app/data/excessive_alcohol.csv") %>%
  rename(state = State)

ufo_alcohol <- ufo %>%
  select(state) %>%
  count(state)

variables <- state.x77 %>%
  as_tibble() %>%
  clean_names() %>%
  select(population, income, illiteracy) %>%
  rename(Population = population) %>%
  rename(Income = income) %>%
  rename(Illiteracy = illiteracy)

alcohol_joined <- inner_join(alcohol, ufo_alcohol) %>%
  mutate(variables) %>%
  rename(Prevalence = Percentage)

model <- stan_glm(data = alcohol_joined,
                n ~ Population + Income + Illiteracy + Prevalence, # Add pluses here to control for more variables.
                family = gaussian(),
                refresh = 0)

table <- tbl_regression(model) %>%
  as_gt() %>%
  tab_header(title = "Regression of Number of UFOs Sighted in Each State",
             subtitle = "The Effect of Population, Income, Illiteracy and Prevalence of Binge Drinking")

table
```
                   
```{r}

read_rds("shiny_app/raw_data/nuforc_reports.rds")
```
                   
```{r visualizations}

ufo %>%
            select(state, shape) %>%
            drop_na() %>%
            filter(shape == "changing" | shape == "chevron" | shape == "cigar" |
                   shape == "circle" | shape == "circle" | shape == "cone" | shape == "cross" |
                   shape == "cylinder" | shape == "diamond" | shape == "disk" |
                   shape == "egg" | shape == "fireball" | shape == "flash" | shape == "formation" |
                   shape == "light" | shape == "other" | shape == "oval" | shape == "rectangle" |
                   shape == "sphere" | shape == "teardrop" | shape == "triangle" | shape == "unknown") %>%
            filter(state == "AL" | state == "AK" | state == "AZ" |
                   state == "AR" | state == "CA" | state == "CO" |
                   state == "CT" | state == "DE" | state == "FL" |
                   state == "GA" | state == "HI" | state == "ID" |
                   state == "IL" | state == "IN" | state == "IA" |
                   state == "KS" | state == "KY" | state == "LA" |
                   state == "ME" | state == "MD" | state == "MA" |
                   state == "MI" | state == "MN" | state == "MS" |
                   state == "MO" | state == "MT" | state == "NE" |
                   state == "NV" | state == "NH" | state == "NJ" |
                   state == "NM" | state == "NY" | state == "NC" |
                   state == "ND" | state == "OH" | state == "OK" |
                   state == "OR" | state == "PA" | state == "RI" |
                   state == "SC" | state == "SD" | state == "TN" |
                   state == "TX" | state == "UT" | state == "VT" |
                   state == "VA" | state == "WA" | state == "WV" |
                   state == "WI" | state == "WY") %>%
            drop_na() %>%
            ggplot(aes(x = state, fill = shape)) +
            geom_histogram(stat = "count") +
            theme_bw() +
            theme(axis.text.x = element_text(angle = 90)) +
            labs(title = "Number of UFO Sightings by State", subtitle = "Don't forget to take the population of each state into account!", 
                 x = "States", y = "Count")


```

```{r}

ufo %>%
  select(state, shape) %>%
  drop_na() %>%
  filter(shape == "changing" | shape == "chevron" | shape == "cigar" |
                   shape == "circle" | shape == "circle" | shape == "cone" | shape == "cross" |
                   shape == "cylinder" | shape == "diamond" | shape == "disk" |
                   shape == "egg" | shape == "fireball" | shape == "flash" | shape == "formation" |
                   shape == "light" | shape == "other" | shape == "oval" | shape == "rectangle" |
                   shape == "sphere" | shape == "teardrop" | shape == "triangle" | shape == "unknown") %>%
  filter(state == "AK") %>%
  ggplot(aes(x = shape, fill = shape)) +
  geom_histogram(stat = "count") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Shapes of UFOs Sighted in States", x = "Shape", y = "Count")
  
```

